"""message

Revision ID: 588f3d81e613
Revises: 166657ba842a
Create Date: 2024-07-09 08:46:20.135932

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '588f3d81e613'
down_revision = '166657ba842a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
